import pyautogui
import time
pyautogui.click(153,879)
pyautogui.write("chrome")
pyautogui.press("enter")
time.sleep(3)
pyautogui.click(628,511)
time.sleep(3)
pyautogui.write("gmail")
pyautogui.press("enter")
time.sleep(3)
pyautogui.click(160,394,)
time.sleep(3)
pyautogui.click(112,250)
time.sleep(3)
pyautogui.write("ga")
pyautogui.press("enter")
pyautogui.press("tab")
pyautogui.write("Python sends you an email")
pyautogui.press("tab")
pyautogui.write("Hello Gabriel, I am Python and I sent you an email.")
pyautogui.press("tab")
pyautogui.press("enter")
